//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace connectData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class aEntities : DbContext
    {
        public aEntities()
            : base("name=aEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<book> book { get; set; }
        public virtual DbSet<c> c { get; set; }
        public virtual DbSet<cj> cj { get; set; }
        public virtual DbSet<myuser> myuser { get; set; }
        public virtual DbSet<s> s { get; set; }
    }
}
